# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
title: Julio's Website
author: Julio Cesar Fausto
author_image: /assets/images/jcfausto.png
description: Julio Cesar Fausto's personal website
baseurl: ""
url: https://jcfausto.com
photo_website: https://jcfausto.net

social:
  - title: github
    url: https://github.com/jcfausto
    icon: github
  - title: linkedin
    url: https://www.linkedin.com/in/jcfausto/
    icon: linkedin

menu:
  - title: Home
    url: /
    target: _self
  - title: Photography
    url: https://jcfausto.net
    target: _blank
  - title: Music
    url: /
    target: _self
  - title: About
    url: /about
    target: _self

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-admin

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
